" todo: add comment block
" todo: change cursors for modes
" todo: change to neo vim
set nocompatible
set backspace=indent,eol,start
syntax enable
set showmatch
set number
set smartindent
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
nnoremap <C-h> :silent set relativenumber! number!<CR>
colorscheme delek 
autocmd FileType make set noexpandtab
" done.
