" todo: add comment block
" todo: change cursors for modes
" todo: change to neo vim

    " basic with CAFs help

set nocompatible
syntax enable
set showmatch
set number
set smartindent
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
nnoremap <C-h> :silent set relativenumber! number!<CR>
autocmd FileType make set noexpandtab

    "no flechas
" Remove newbie crutches in Command Mode
cnoremap <Down> <Nop>
cnoremap <Left> <Nop>
cnoremap <Right> <Nop>
cnoremap <Up> <Nop>

" Remove newbie crutches in Insert Mode
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
inoremap <Up> <Nop>

" Remove newbie crutches in Normal Mode
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
nnoremap <Up> <Nop>


" Remove newbie crutches in Visual Mode
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>
vnoremap <Up> <Nop>

    " Change cursor

:autocmd InsertEnter * set cul 
:autocmd InsertLeave * set nocul

    " done.


