" Maintainer: VRA,PB;CAF
" Date: Oct.7 
" License: (c) VRA, GPL-2 or newer
" --------------------------------------------------
" dotfiles/vim/vimrc

" basic with CAFs help
let maplocalleader = ','
colo desert
syntax on

set nocompatible
set cursorline
syntax enable
set showmatch
set number
set relativenumber
set colorcolumn=80
set textwidth=80
set smartindent
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set list
set listchars=tab:▸\ ,eol:¬,nbsp:·,trail:·
nnoremap <C-h> :silent set relativenumber! number!<CR>
autocmd FileType make set noexpandtab

"no gets en R
let R_assign = 0

"no flechas
" Remove newbie crutches in Command Mode
cnoremap <Down> <Nop>
cnoremap <Left> <Nop>
cnoremap <Right> <Nop>
cnoremap <Up> <Nop>

" Remove newbie crutches in Normal Mode
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
nnoremap <Up> <Nop>


" Remove newbie crutches in Visual Mode
vnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>
vnoremap <Up> <Nop>

" Change cursor

:autocmd InsertEnter * set cul 
:autocmd InsertLeave * set nocul

" close brackets/parens/quotes
inoremap ( ()<C-G>U<Left>
inoremap [ []<C-G>U<Left>
inoremap { {}<C-G>U<Left>
inoremap <expr>) getline('.')[col('.')-1] == ")" ? "\<C-G>U<Right>" : ")"
inoremap <expr>] getline('.')[col('.')-1] == "]" ? "\<C-G>U<Right>" : "]"
inoremap <expr>} getline('.')[col('.')-1] == "}" ? "\<C-G>U<Right>" : "}"

" plugs
call plug#begin('~/.local/share/nvim/plugged')
Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-github'
Plug 'ncm2/ncm2-syntax'
Plug 'ncm2/ncm2-jedi'
Plug 'ncm2/ncm2-vim'
Plug 'ervandew/supertab'
Plug 'luochen1990/rainbow'
Plug 'godlygeek/tabular'
Plug 'jalvesaq/Nvim-R'
call plug#end()

" Taraks shortcuts
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect

let g:rainbow_active = 1 "set to 0 if you want to enable it later via :RainbowToggle
let g:ale_linters = {
\    'python': ['flake8']
\}
let g:airline_theme='sol'


